import os
import sys

import eol_scons

tools = ['qmicromap','doxygen','prefixoptions']

env = Environment(tools = ['default'] + tools)

env.Uic4('QMicroMapTest.ui')

env.Replace(CCFLAGS=['-g','-O2'])

sources = ['qmmtest.cpp','QMicroMapTest.cpp']

test = env.Program('qmmtest', sources)
env.Default(test)