import os
import sys

import eol_scons

tools = ['qmicromap','doxygen','prefixoptions']

env = Environment(tools = ['default'] + tools)

sources = ['qmmtest.cpp',]

test = env.Program('qmmtest', sources)
env.Default(test)