# -*- python -*-

tools = [
'default',
'doxygen',
'spatialdb',
'sqlitedb',
'qmicromap'
]

env = Environment(tools = tools)

demo1 = env.Program('demo1', 'demo1.cpp')
demo2 = env.Program('demo2', 'demo2.cpp')
demo3 = env.Program('demo3', 'demo3.cpp')
demo4 = env.Program('demo4', 'demo4.cpp')
spatialtest = env.Program('spatialtest', 'spatialtest.cpp')

env.Default(demo1)
env.Default(demo2)
env.Default(demo3)
env.Default(demo4)

env.Default(spatialtest)
